version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: replyMate_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: psql
    ports:
      - "9432:5432" # Maps container port 5432 to host port 5432
    volumes:
      - /Users/hariventmohan/projects/replyMate/script/psql:/var/lib/postgresql3/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: replyMate_pgadmin
    ports:
      - "9252:80"

    volumes:
      - /Users/hariventmohan/projects/replyMate/script/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: mhariventan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin1
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER$


